# Generated by Django 3.2.9 on 2021-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_login_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
