# Generated by Django 3.2.9 on 2021-11-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='id',
            new_name='id2',
        ),
    ]
