# Generated by Django 2.2.1 on 2021-11-17 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_item_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
