# Generated by Django 3.2.9 on 2021-11-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_id_login_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id2',
        ),
        migrations.AddField(
            model_name='login',
            name='user_email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='user_validation',
            field=models.BooleanField(default=False),
        ),
    ]
