# Generated by Django 3.2.9 on 2021-11-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20211119_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to=settings.AUTH_USER_MODEL),
        ),
    ]
