# Generated by Django 3.2.9 on 2021-11-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_login_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('test1', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('test2', models.CharField(max_length=50)),
            ],
        ),
    ]
