# Generated by Django 3.2.9 on 2021-11-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
